spring:
  #git配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xutc1996/config-server
          username: xutc1996
          password: xtc2516888
          timeout: 5
          default-label: master

#服务端口号
server:
  port: 9100
