server:
  port: 8781

#服务名称
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    database: 0

#自定义负载均衡策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#feign设置超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
  hystrix:
    enabled: true

#设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#暴露全部的Dashboard监控仪表盘信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
